### ISSUE TITLE
关于 detect_uri() 方法实现步骤中具体的应用场景

### ISSUE THREAD

**Issue by RainScorpio** [if-information/PHP_Framework_CodeIgniter#1]
```php

function detect_uri() {
     
     if ( ! isset($_SERVER['REQUEST_URI']) OR ! isset($_SERVER['SCRIPT_NAME'])) {
        return '';
     }
 
    $uri = $_SERVER['REQUEST_URI'];

     if (strpos($uri, $_SERVER['SCRIPT_NAME']) === 0) {
         $uri = substr($uri, strlen($_SERVER['SCRIPT_NAME']));
     }
 
    if ($uri == '/' || empty($uri)) { // 为什么要使用empty($uri)判断, 有什么具体的使用场景吗?
        return '/';
     }

    $uri = parse_url($uri, PHP_URL_PATH);

     // 将路径中的 '//' 或 '../' 等进行清理
     return str_replace(array('//', '../'), '/', trim($uri, '/'));
}

```
 
@yuancaoscott

**Comment by RainScorpio** [comment]
```php
// 通过下面的URL, 查看结果
// http://localhost/index.php/module/controller/action/index?name=tom

var_dump($_SERVER['REQUEST_URI']);

var_dump(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));


var_dump($_SERVER['SCRIPT_NAME']);

$uri = substr($_SERVER['REQUEST_URI'], strlen($_SERVER['SCRIPT_NAME']));

var_dump($uri);

var_dump(parse_url($uri, PHP_URL_PATH));

```

**Comment by yuancaoscott** [comment]
什么情况下 `$_SERVER['REQUEST_URI']` 和 `$_SERVER['SCRIPT_NAME']` 为空?

**Comment by yuancaoscott** [comment]
### 对 `uri` 字符串进行处理,  得到不包含 scheme,  主机名,  脚本文件名, 参数的字符串.

#### 首先了解常用的变量和 `parse_url` 函数返回值: 
假设 `uri` 为 `http://localhost/index.php/module/controller/action/index?name=tom`

* `$_SERVER['REQUEST_URI']` :  /index.php/module/controller/action/index?name=tom
* `$_SERVER['SCRIPT_NAME']` :  /index.php
* `parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)` : /index.php/module/controller/action/index

#### 最终得到不包含 scheme,  主机名,  脚本文件名, 参数的字符串

```php

<?php

$uri = 'http://localhost/index.php/module/controller/action/index?name=tom';

// 从uri中去掉脚本部分
$uri = substr($_SERVER['REQUEST_URI'], strlen($_SERVER['SCRIPT_NAME']));

// 再去掉参数部分
$uri = parse_url($uri, PHP_URL_PATH);

var_dump($uri);  // 结果: /module/controller/action/index

}
```

**Comment by yuancaoscott** [comment]
### `if ( !isset($_SERVER['REQUEST_URI']) OR !isset($_SERVER['SCRIPT_NAME'])) ` 判断语句的解析

```php

function detect_uri() {
      
    if ( !isset($_SERVER['REQUEST_URI']) OR !isset($_SERVER['SCRIPT_NAME'])) {
        return '';
    }

}
```

` if (!表达式1 OR !表达式2)` 会有三种可能情况其中
表达式1为 ` isset($_SERVER['REQUEST_URI'])`
表达式2为 `isset($_SERVER['SCRIPT_NAME'])`
   
* 第一种可能情况:
   1. 如果 `$_SERVER['REQUEST_URI']` 值没有设置或为空, `isset` 返回值为false, `!isset` 返回值为true
   2. 不进行 OR 后面的表达式判断, if条件成立, 进入代码块中, `detect_uri` 函数返回 `''`
  
*  第二种可能情况:
   1. 如果 `$_SERVER['REQUEST_URI']` 的值设置了且非空, `isset` 返回值为true, `!isset` 返回值为false
   2. 继续判断 `$_SERVER['SCRIPT_NAME']` 的值, 如果此值设置了且非空, `isset` 返回值为true, `!isset` 为false,
   3. false OR false 为 false, if条件不成立, 不进入代码块中.

* 第三种可能情况:
   1. 如果 `$_SERVER['REQUEST_URI']` 的值设置了且非空, `isset` 返回值为true, `!isset` 返回值为false
   2. 再判断 `$_SERVER['SCRIPT_NAME']` 的值, 如果此值没有设置或为空, `isset` 返回值为false, `!insset` 返回值为true
   3. flase OR true 为 true, if条件成立, 进入代码块中. `detect_uri` 函数返回 `''`

* 通过对上面的3个可能情况分析, 得出要使if条件不成立必须满足:
   1. `$_SERVER['REQUEST_URI']` 值设置了且非空
   2. `$_SERVER['SCRIPT_NAME']` 值设置了且非空

* 或者说只要 `$_SERVER['REQUEST_URI']` 和 `$_SERVER['SCRIPT_NAME']` 有一个未设置或为空, `detect_uri` 函数直接返回 ` ''`

**Comment by yuancaoscott** [comment]
### `if ($uri == '/' || empty($uri))` 判断语句的解析
```php
function detect_uri() {
         
    if ($uri == '/' || empty($uri)) { // 为什么要使用empty($uri)判断, 有什么具体的使用场景吗?
        return '/';
     }

}
```

* 如果 `uri` 是 `http://localhost/index.php/`
`$_SERVER['REQUEST_URI']` 是 /index.php/
`$_SERVER['SCRIPT_NAME']` 是 /index.php
`$uri` 为 `/`

* 如果 `uri` 是 `http://localhost/index.php`
`$_SERVER['REQUEST_URI']` 是 /index.php
`$_SERVER['SCRIPT_NAME']` 是 /index.php
`$uri` 为 空

**Comment by yuancaoscott** [comment]
### `detect_uri() ` 函数作用
检测请求中的 `uri`, 并从 `uri` 中删除 scheme, 主机名, 脚本文件名, 参数等, 其中包含以下可能情况:
* 如果 `uri` 中  `$_SERVER['REQUEST_URI']` 和 `$_SERVER['SCRIPT_NAME']` 有一个未设置或值为空,  返回 `''` 空字符串.
* 如果 `uri` 中只到 `$_SERVER['SCRIPT_NAME']`, 例如: `http://localhost/index.php`, `http://localhost/index.php/` , 返回 `/` 字符串.
* 其它情况下的 `uri`, 将删除scheme, 主机名, 脚本文件名, 参数等. 并去掉收尾的 `/` 符号. 同时中间的 `// `, `../` 全部替换为 `/`

**Comment by RainScorpio** [comment]
```php
// 将路径中的 '//' 或 '../' 等进行清理
     return str_replace(array('//', '../'), '/', trim($uri, '/'));
```

先执行`str_replace()`函数替换`$uri`字符串中的 '//'或'../',  再执行函数`trim()`函数去掉开头结尾的'/' **是不是会更好些???**

**Comment by RainScorpio** [comment]
```php
// 将路径中的 '//' 或 '../' 等进行清理
     return str_replace(array('//', '../'), '/', trim($uri, '/'))
```

为什么只是替换 '//' 和 '../'?

如果只是为了防止用户乱写, 那还有可能乱写其他字符啊, 比如 '///' 等.

如果访问路径是 `http://localhost:8070/01_URL/index.php//admin/login/index?name=Tom` (admin前面有 // ) 最终得到的是 `/login/index`字符串, 而不是预想中的 `admin/login/index`

**Comment by RainScorpio** [comment]
```php

 if (strpos($uri, $_SERVER['SCRIPT_NAME']) === 0) {
         $uri = substr($uri, strlen($_SERVER['SCRIPT_NAME']));
     }

```

什么情况下` strpos($uri, $_SERVER['SCRIPT_NAME'])` 会返回 `false`?

返回`false`的情况下, 还能得到我们想要的结果了吗???

**Comment by yuancaoscott** [comment]
@RainScorpio 
`detect_url` 函数处理 `http://localhost:8070/01_URL/index.php//admin/login/index?name=Tom`时
* 经过 `$uri = substr($uri, strlen($_SERVER['SCRIPT_NAME']));` 语句处理后, 
`uri` 为 `//admin/login/index?name=Tom`
* 经过  `$uri = parse_url($uri, PHP_URL_PATH);` 语句处理后, 
`uri` 为 `/login/index`
* 经过 `str_replace(array('//', '../'), '/', trim($uri, '/'))` 语句处理后, 
得到 `login/index`

所以, 是中间的 `$uri = parse_url($uri, PHP_URL_PATH);` 语句截掉了 `//admin` 字段

**Comment by RainScorpio** [comment]
我知道 `//admin` 为什么被截掉了.   我只是针对 detect_uri() 方法 提出了一个反例, 证明这个方法还不够严谨.

**Comment by yuancaoscott** [comment]
@RainScorpio 

> 先执行str_replace()函数替换$uri字符串中的 '//'或'../', 再执行函数trim()函数去掉开头结尾的'/' 是不是会更好些???

假设`uri` 为 `http://localhost/index.php/admin/login/login///`
在调用 `str_replace()` 函数之前, `uri` 为 `/admin/login/login///`
如果这种情况下, 先调用 `trim` , 再调用 `str_replace` ,  效率会高些

**Comment by RainScorpio** [comment]
@yuancaoscott 

1. 为什么效率会更高?

2. 这种情况是不是一种特殊情况? 如果 `$uri` 是 `/admin/login/login////` 的话, 是不是 先 `str_replace`, 再`trim()`效率会更高?

**Comment by yuancaoscott** [comment]
@RainScorpio 
> 1. 为什么效率会更高?
> 2. 这种情况是不是一种特殊情况? 如果 $uri 是 /admin/login/login//// 的话, 是不是 先 str_replace, 再trim()效率会更高?

可以对 `str_replace` `trim` 函数进行一下测试

* 测试条件：同一个字符串 `'(name)'` 替换 `()`
```php
/* * 
 *  测试内容：str_replace trim 效率
 */
function test($str, $func)
{
    $start_time = microtime(true);
    for ($i = 0; $i < 10000; $i++) {
        $v = $func($str);
    }
    $end_time = microtime(true);
    echo($end_time - $start_time), '<br>';
}


$str = '(name)';

//测试 str_replace
test($str, function ($p) {
    return str_replace('(', '', str_replace(')', '', $p));
});
// 测试 trim
test($str, function ($p) {
    return trim($p, '()');
});
```

结果: 
```php
0.051465034484863
0.039777994155884
```

测试结论:
 *  非正则下 效率 `trim` > `str_replace`

我认为先对字符串调用 `trim`, 再调用 `str_replace` 比较合理

**Comment by RainScorpio** [comment]
```php
function test($str, $func)
{
    $start_time = microtime(true);
    for ($i = 0; $i < 10000; $i++) {
        $v = $func($str);
    }
    $end_time = microtime(true);
    echo($end_time - $start_time), '<br>';
}


$uri = '//admin/login/index/';

// 先执行trim(), 再执行 str_replace()
test($uri, function ($p) {
   return str_replace(array('//', '../'), '/', trim($p, '/'));
//    return str_replace('(', '', str_replace(')', '', $p));
});

// 先执行str_replace(), 再执行trim()
test($uri, function ($p) {
    return trim(str_replace(array('//', '../'), '/', $p), '/');

//    return trim($p, '()');
});


/**
 * 相同的代码, 运行三次的结果:
 * 
 * 第一次
 *  0.0071258544921875
 *  0.0075809955596924
 *
 * 第二次
 *  0.0071249008178711
 *  0.0071949958801277
 *
 * 第三次
 *  0.008552074432373
 *  0.0073089599609375
 *
 */

```


其实我想说先执行str_replace()后执行trim()函数, 更多的含义是在代码逻辑上的好处

**Comment by yuancaoscott** [comment]
@RainScorpio 
> 其实我想说先执行str_replace()后执行trim()函数, 更多的含义是在代码逻辑上的好处

能说说代码逻辑上的好处吗

**Comment by RainScorpio** [comment]
目前还没有任何的思路, 不知道为什么这么写 ` return str_replace(array('//', '../'), '/', trim($uri, '/'));`

代码含义我明白, 我只是不知道这么写代码的具体使用场景, 所以产生了疑问

**Comment by yuancaoscott** [comment]
@RainScorpio 
> `return str_replace(array('//', '../'), '/', trim($uri, '/'));`

同感, 暂时没有找出使用场景.

**Comment by RainScorpio** [comment]
# 总结

经过 PHP小组第1次技术讨论会 讨论, 做出如下总结:

    1. detect_uri() 函数的实现思路在以上讨论中已经解释的很清晰, 这里不再总结

    2. 对 `return str_replace(array('//', '../'), '/', trim($uri, '/'));` 这段代码已经达到基本目的, 对使用场景和先后顺序不再纠结.
