### ISSUE TITLE
Step1中的 OR 逻辑运算符的"隐藏属性"!

### ISSUE THREAD

**Issue by RainScorpio** [if-information/PHP_Framework_CodeIgniter#10]
1. PHP逻辑运算符的两大阵营: 
   *  `&&`, `||`, `!` 
   *  `and`, `or`, `xor`

2.  `and`, `or`, `xor` 都有什么用处?

**Comment by RainScorpio** [comment]
# PHP逻辑运算符

> [PHP 逻辑运算符](http://php.net/manual/zh/language.operators.logical.php)

## 逻辑运算符的作用

例子 | 名称 | 结果
-- | -- | --
$a and $b | And（逻辑与） | TRUE，如果 $a 和 $b 都为 TRUE。
$a or $b | Or（逻辑或） | TRUE，如果 $a 或 $b 任一为 TRUE。
$a xor $b | Xor（逻辑异或） | TRUE，如果 $a 或 $b 任一为 TRUE，但不同时是。
! $a | Not（逻辑非） | TRUE，如果 $a 不为 TRUE。
$a && $b | And（逻辑与） | TRUE，如果 $a 和 $b 都为 TRUE。
$a \|\| $b | Or（逻辑或） | TRUE，如果 $a 或 $b 任一为 TRUE。

## 区别

> [PHP 运算符优先级](http://php.net/manual/zh/language.operators.precedence.php)


下表按照优先级从高到低列出了运算符。同一行中的运算符具有相同优先级，此时它们的结合方向决定求值顺序

结合方向 | 运算符 | 附加信息
-- | -- | --
右 | ! | 逻辑运算符
左 | && | 逻辑运算符
左 | \|\| | 逻辑运算符
right | = += -= *= **= /= .= %= &= \|= ^= <<= >>= | 赋值运算符
左 | and | 逻辑运算符
左 | xor | 逻辑运算符
左 | or | 逻辑运算符




### 区别就是  **`&&` 和 `||` 的优先级 比 `and`, `or`, `xor` 高**

```php
// "&&" 比 "and" 的优先级高

// 表达式 (true && false) 的结果被赋给 $g
// 等同于：($g = (true && false))
$g = true && false;

// 常量 true 被赋给 $h，false 被忽略
// 等同于：(($h = true) and false)
$h = true and false;

var_dump($g, $h); 
// 输出: 
// bool(false)
// bool(true)
```

**Comment by RainScorpio** [comment]
# and, or, xor 都有什么用处?

答案在这里  [PHP的低优先级逻辑运算符](https://www.web-tinker.com/article/20121.html), 快来围观啊!

> 因为这篇博客中列举得案例都非常好, 所以我就不再赘述了!

**Comment by yuancaoscott** [comment]
@RainScorpio 
> && 和 || 的优先级 比 and, or, xor 高
> ...
> $g = true && false;
> ...
> $h = true and false;
> ...

这两个例子中 `&&` 和 `and` 没有同时出现在一个表达式中, 所以 
`&& 和 || 的优先级 比 and, or, xor 高`  换成`&& 优先级高于赋值运算符 =,  and 优先级低于赋值运算符 = `是不是更好一些.

**Comment by RainScorpio** [comment]
@yuancaoscott 
> && 和 || 的优先级 比 and, or, xor 高 换成&& 优先级高于赋值运算符 =, and 优先级低于赋值运算符 =是不是更好一些.

对于这个问题, 做出以下三点回复:

1. 在代码示例中,   "&& 优先级高于赋值运算符 =, and 优先级低于赋值运算符 =" 的说法的确要比 ""&&" 比 "and" 的优先级高" 的说法更严谨. 

2. 代码示例摘自 官网的[PHP 逻辑运算符](http://php.net/manual/zh/language.operators.logical.php). 着重体现的是 两种逻辑运算符的区别, 所以当时并没有深入考虑这个问题. 感谢提醒!🤝

3. 我着重想要表达的是 **PHP中两种逻辑运算符的区别**, 和 ` =` 赋值运算符没有关系, 只是在代码示例中使用了`=`.  所以我认为对于  **"PHP中两种逻辑运算符的区别"** 的描述, **"&& 和 || 的优先级 比 and, or, xor 高"**   更合适, 而这也是事实.
