### ISSUE TITLE
$per2=$per1 和 $per2=&$per1 是否完全相同?

### ISSUE THREAD

**Issue by RainScorpio** [if-information/PHP_Framework_CodeIgniter#11]
> 此问题从 #8 中引申而来

```php
<?php

class Person
{
    public $name = '';
    public function __construct($name)
    {
        $this->name = $name;
    }

    public function info()
    {
        echo $this->name . '<br>';
    }
}

$per1 = new Person('Tom');

$per2 = $per1; // 此处如果赋值是引用即 $per2 = &$per1, 下面的结果还是一样 , 所以 $per2 = $per1 就是引用赋值, 不是值赋值.  & 此处意义不大, 可以省略
$per2->name = 'lisi';
$per1->info(); // 输出 Tom
$per2->info(); // 输出 Tom
```

以上代码中 `$per2=$per1` 和 `$per2=&$per1` 是否完全相同? 

比如在代码含义, 内存管理等方面是否完全相同?

**Comment by FrigidCrow** [comment]
# C01_结果相同

首先, 可以说`$per2=$per1` 和 `$per2=&$per1` 这两种方式所产生的结果是完全相同的, 但是在代码含义, 或者说在他的意义上是不相同的, 这是明显的, 按值传递还是按引用传递的区别.
按值传递就是仅仅把值传递过去，相当于传递的是值的拷贝，而按引用传递传递的是内存的地址.
如果是按值传递, 就是将 zval 的地址赋给另一个变量，这时，两个变量都同时指向一个 zval 。而按值传递则是复制一个 zval，两个变量指向两个不同的 zval. (zval 一切变量的容器)
真正保存对象的结构是 zend_object，一个变量（zval）里实际保存的是指向该结构体的指针。传递这个变量时，就是拷贝该指针的副本，而这个指针指向存储堆区的对象.
可以说PHP这点和C是及其相似了

**Comment by yuancaoscott** [comment]
# C02_是否会产生内存泄漏的问题?

@RainScorpio 
> 比如在代码含义, 内存管理等方面是否完全相同?

你是否是想说内存管理方面的不同, 是引用计数还是垃圾回收, 是否会产生内存泄漏的问题?

**Comment by RainScorpio** [comment]
# C03_对象和引用

> [引用的解释](http://php.net/manual/zh/language.references.php)
>
> [对象和引用](http://php.net/manual/zh/language.oop5.references.php)
> &nbsp;&nbsp;&nbsp;&nbsp;在php5 的对象编程经常提到的一个关键点是“默认情况下对象是通过引用传递的”。但其实这不是完全正确的。下面通过一些例子来说明。


```php

class A {
    public $foo = 1;
}

$a = new A;
$b = $a;     // $a ,$b都是同一个标识符的拷贝
// ($a) = ($b) = <id>
$b->foo = 2;
var_dump('$a->foo');
echo $a->foo."\n"; // 2

// 直接修改变量b本身
$b = 'change b'; 
var_dump($a);  // $a没有因为$b改变而改变. 
//输出: class A#1 (1) {
//      public $foo =>
//      int(2)
//      }




$c = new A;
$d = &$c;    // $c ,$d是引用
// ($c,$d) = <id>

$d->foo = 2;
var_dump('$c->foo');
echo $c->foo."\n"; // 2

// 修改变量d本身
$d = 'change d';
var_dump($c); // 输出: change d
```

**Comment by RainScorpio** [comment]
# 总结

经过PHP小组第2次会议讨论, 总结如下:

1. `$per2 = $per1` 和 `$per2 = &per1` 是不同的两种赋值方式, 只是最终可以访问到相同的内容而已. 实际编译时有很大的不同.

2. 有关PHP引用的讨论已经转移到 if_PHP仓库的  [PHP的引用 #1](https://github.com/if-information/if_PHP/issues/1)的Issue.
