### ISSUE TITLE
URI 和 URL 区别?

### ISSUE THREAD

**Issue by yuancaoscott** [if-information/PHP_Framework_CodeIgniter#5]
URI: 统一资源标识符（Uniform Resource Identifier)
URL: 统一资源定位符 (Uniform Resource Locator)
它们的区别是什么?

**Comment by FrigidCrow** [comment]
# C01_url和uri的区别

我认为, 一句话概括
 url和uri的区别:  URI 和 URL 都定义了 what the resource is, URL 还定义了 how to get the resource

举例:
一个网址包http: // http://www.xxx.com/dir/filename.html 中/dir/filename.html就是uri 而整个连接又是url，url包含了指定什么协议（http），在哪个站点（http://www.xxx.com）获得什么资源（/dir/filename.html)

**Comment by yuancaoscott** [comment]
# C02_绝对URI和相对URI

赞同
@FrigidCrow 的
> url和uri的区别: URI 和 URL 都定义了 what the resource is, URL 还定义了 how to get the resource

但
> 举例:
一个网址 http://www.xxx.com/dir/filename.html 中/dir/filename.html就是uri 而整个连接又是url，url包含了指定什么协议（http），在哪个站点（http://www.xxx.com）获得什么资源（/dir/filename.html)

准确的描述应该为: 
* 绝对URI = `http://www.xxx.com/dir/filename.html`
* 相对URI = `/dir/filename.html`
* URL = `http://www.xxx.com/dir/filename.html`

## RFC 2396 文档中对URI的完整定义

[RFC 2396 : Uniform Resource Identifiers (URI): Generic Syntax](http://www.ietf.org/rfc/rfc2396.txt)

几个重要术语:
* Hierarchical URI (分层URI)
* scheme (一般翻译为方案)
* URI-reference
   语法: `URI-reference = [ absoluteURI | relativeURI ] [ "#" fragment ]`
* absoluteURI (绝对URI)
   语法: `absoluteURI   = scheme ":" ( hier_part | opaque_part )`
* relative URI (相对URI)
   语法: `relativeURI   = ( net_path | abs_path | rel_path ) [ "?" query ]`

文档中 section 3 中定义了绝对URI的语法, 如下
`<scheme>:<scheme-specific-part>`

紧接着文档指出
> The URI syntax does not require that the scheme-specific-part have
   any general structure or set of semantics which is common among all
   URI.  However, a subset of URI do share a common syntax for
   representing hierarchical relationships within the namespace.  This
   "generic URI" syntax consists of a sequence of four main components:

文档给出了"通用 URI" 语法:
`<scheme>://<authority><path>?<query>`

文档中 3.2 部分描述了 `authority`  部分的语法
`authority  = server | reg_name`

文档中 3.2.2 部分描述了 `server` 部分的语法
`<userinfo>@<host>:<port>`

将上述的几个部分组合起来, 会得到我们常见的URI形式.
`<scheme>://<userinfo>@<host>:<port><path>?<query>`

文档在 3.2 最后一段指出:
> An authority component is not required for a URI scheme to make use
   of relative references.  A base URI without an authority component
   implies that any relative reference will also be without an authority
   component.

也就说, 在相对URI中, 不含有 `<scheme>`  和 `<authority>` 部分.  即
`relativeURI   = ( net_path | abs_path | rel_path ) [ "?" query ]`

我们PHP中常用的 `$_SERVER["REQUEST_URI"]` 获取出来的是相对URI(relativeURI)

**Comment by RainScorpio** [comment]
# C03_URI 和 URL的关系 

> 来源:  [WIKI 统一资源标志符](https://zh.wikipedia.org/wiki/%E7%BB%9F%E4%B8%80%E8%B5%84%E6%BA%90%E6%A0%87%E5%BF%97%E7%AC%A6)

```
URI的最常见的形式是统一资源定位符（URL）
```

> 其他参考资料: [URIs, URLs, and URNs: Clarifications and Recommendations 1.0](https://www.w3.org/TR/uri-clarification/)

**Comment by RainScorpio** [comment]
# C04_URI 例子 

> <图解HTTP> 第1章 了解Web及网络基础  P17

"RFC3986: 统一资源标识符(URI)通用语法" 中列举了集中URI例子, 如下所示

```
ftp://ftp.is.co.za/rfc/rfc1808.txt

http://www.ietf.org/rfc/rfc2396.txt

ldap://[2001:db8::7]/c=GB?objectClass?one

mailto:John.Doe@example.com

news:comp.infosystems.www.servers.unix

tel:+1-816-555-1212

telnet://192.0.2.16:80/

urn:oasis:names:specification:docbook:dtd:xml:4.1.2
```

**Comment by RainScorpio** [comment]
# 总结

经过PHP小组第2次会议讨论, 总结如下:

1.  URL是URI的一种子类. URI还包含其他子类, 比如URN等.  

2.  URL是URI最常见的一种形式, 所以也可以将URL称为URI, 但不能把URI称之为URL.

3.  URI分为 绝对URI 和 相对URI (详情参考C02), URL并没有绝对和相对之分.

4.  URI实际例子参考C04.
