### ISSUE TITLE
CodeIgniter框架(1)的explode_uri函数中的preg_replace函数问题

### ISSUE THREAD

**Issue by FrigidCrow** [if-information/PHP_Framework_CodeIgniter#7]
实际测试, 以`http://localhost/testCodeIgniter/index.php/as/d/zxc///`为例, 经过`detect_url`函数的处理其结果已经是`as/d/zxc`, 在后面又用preg_replace函数处理了一次, 但是其结果没有丝毫改变, 经目前状况, 我只能认为preg_replace属于无用函数, 除非有反例出现.

**Comment by yuancaoscott** [comment]
目前来看 `preg_replace` 函数没有起到作用. 

在CI的源代码中, `preg_replace('|/*(.+?)/*$|', '\\1', BASEPATH))` 只在 `/system/core/Config.php` 出现过一次
```php
public function system_url()
	{
		$x = explode('/', preg_replace('|/*(.+?)/*$|', '\\1', BASEPATH));
		return $this->slash_item('base_url').end($x).'/';
	}
```

后面会持续关注这个正则表达式.

**Comment by RainScorpio** [comment]
# 整段代码已被移除
> https://github.com/bcit-ci/CodeIgniter/commit/edbbc7dfc01ce05a1c37629df0e1b4c8d00c435f#diff-c67c712859c7ff8b44fc6b1d6e6b7e97

以下代码已从源码中整体移除

```php
public function system_url()
	{
		$x = explode('/', preg_replace('|/*(.+?)/*$|', '\\1', BASEPATH));
		return $this->slash_item('base_url').end($x).'/';
	}

```

**Comment by FrigidCrow** [comment]
移除原因是
`encourages  insecure practices`
鼓励不安全行为? 不是很明白, 等会可以讨论一下

**Comment by yuancaoscott** [comment]
# 一级标题效果

**Comment by yuancaoscott** [comment]
## 二级标题效果

**Comment by yuancaoscott** [comment]
### 三级标题效果

**Comment by RainScorpio** [comment]
# 总结

经过PHP小组第2次会议讨论, 总结如下:

1.  此Issue中提出的问题是代码的具体应用场景而非理论原因. 
2.  鉴于官方已经将此段代码删除, 并且目前无法得知具体使用场景, 所以将此Issue关闭, 不再进行讨论.
